### ISSUE TITLE
Sudden jumps at transient ocean current interpolation

### ISSUE THREAD

**Issue by woensug-choi** [Field-Robotics-Lab/dave#105]
Sudden jumps at the topic published from the ocean current plugin are observed. I suspect it's a division error or int/double error. But not sure why exactly now.

To reproduce, 
- Repositories
  - dave : master (commit : 4623fe56f75730b6233f9f9c651358fd21dc2379)
  - glider_hybrid_whoi : 'two_gliders' branch (commit : 30bb4312b67cff9a82304700d47a49c38447ab52)
- Launch command
  - `roslaunch glider_hybrid_whoi_gazebo start_demo_kinamtics_stratified_current.launch`
- Monitering
  - Through gazebo window, the glider teleports at random time
  - Transinet ocean current topic shows sudden jumps at it's value while it should be constant at constant depth.
     - `rostopic echo /hydrodynamics/current_velocity/glider_hybrid_whoi`
- Sudden jump happens randomly, sometimes at 8 seconds after the launch and other times at different time.

Example
- Correct value interpolated at its depth
```
header: 
  seq: 907
  stamp: 
    secs: 90
    nsecs: 900000000
  frame_id: "/world"
twist: 
  linear: 
    x: 0.00799999999868
    y: 0.00802509638012
    z: 0.0
  angular: 
    x: 0.0
    y: 0.0
    z: 0.0
```
- Sudden jumps appeared at random time
```
header: 
  seq: 908
  stamp: 
    secs: 91
    nsecs:         0
  frame_id: "/world"
twist: 
  linear: 
    x: 0.01
    y: 0.0100250963814
    z: 0.0
  angular: 
    x: 0.0
    y: 0.0
    z: 0.0
```
